SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS shop DEFAULT CHARACTER SET utf8mb4;
USE shop;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS shop_user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  login VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL,
  role VARCHAR(8) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS item (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  price DECIMAL(8,2) NOT NULL,
  available_quantity INT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS cart (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  status VARCHAR(8) NOT NULL,
  last_update DATETIME,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES shop_user(id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS cart_item (
  id BIGINT NOT NULL AUTO_INCREMENT,
  cart_id BIGINT NOT NULL,
  item_id BIGINT NOT NULL,
  ordered_quantity INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (cart_id) REFERENCES cart(id),
  FOREIGN KEY (item_id) REFERENCES item(id)
)
ENGINE = InnoDB;

CREATE INDEX login
ON shop_user (login);

CREATE INDEX name
ON item (name);

CREATE INDEX price
ON item (price);

CREATE INDEX status
ON cart (status);

CREATE TRIGGER cart_date_on_create BEFORE INSERT ON cart
FOR EACH ROW
SET NEW.last_update = NOW();

CREATE TRIGGER cart_date_on_update BEFORE UPDATE ON cart
FOR EACH ROW
SET NEW.last_update = NOW();

CREATE TRIGGER cart_item_cart_date_on_create BEFORE INSERT ON cart_item
FOR EACH ROW
UPDATE cart
SET cart.last_update = NOW()
WHERE cart.id = NEW.cart_id;

CREATE TRIGGER cart_item_cart_date_on_update BEFORE UPDATE ON cart_item
FOR EACH ROW
UPDATE cart
SET cart.last_update = NOW()
WHERE cart.id = NEW.cart_id;

CREATE TRIGGER cart_item_cart_date_on_delete BEFORE DELETE ON cart_item
FOR EACH ROW
UPDATE cart
SET cart.last_update = NOW()
WHERE cart.id = OLD.cart_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
